name: flutter_application_stresscheck
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0 # 여기에 intl 패키지를 추가합니다.
  http: ^1.2.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - image/
